### PR TITLE
clisp: make INPUT-STREAM-P and OUTPUT-STREAM-P generic functions

### PR DESCRIPTION
**Pull request by dkochmanski**

### CODE REVIEW

**Comment by avodonosov** [comment]
Thanks for the patch, but why is it useful? The Gray proposal (http://www.nhplace.com/kent/CL/Issues/stream-definition-by-user.html) says "These three existing predicates may optionally be implemented as generic functions for implementations that want to permit users to define streams that are not STANDARD-OBJECTs"

Optionally. So CLISP is conforming even it the functions are not generic.

How does making the fns generic help?

**Comment by dkochmanski** [comment]
Most implementations (abcl and clisp are the exceptions here, and ecl needs gray:redefine-cl-functions) provide them as generic functions. I think that consistent behaviour would be best for trivial-gray-streams, but indeed, this is intrusive approach.

Should I prepare similar fix for abcl, or just revoke the PR?

**Comment by avodonosov** [comment]
What is a use case for these functions as generic functions? Do you know why McCLIM redefine them?

**Comment by dkochmanski** [comment]
it specializes them on its standard-encapsulating-stream with some custom mechanism (I'm not sure what it does though)

https://github.com/robert-strandh/McCLIM/blob/master/encapsulate.lisp#L69
https://github.com/robert-strandh/McCLIM/blob/master/encapsulate.lisp#L117

**Comment by dkochmanski** [comment]
I've asked, if McCLIM could drop this assumption to keep things clean.
(cross-ref: https://github.com/robert-strandh/McCLIM/issues/15)

**Comment by dkochmanski** [comment]
it's because CLIM II mandates these functions to be generic in it's own specification. I suppose McCLIM will have to provide it's own hacks of this. I'm closing the issue (closed the cross-ref too).

**Pull request closed without merging**
